version: '3.7'

services:
  api:
    container_name: pendura_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  redis:
    container_name: pendura_redis
    image: redis
    ports:
      - 6379:6379
    command: redis-server --requirepass redis
    networks:
      - backend
  postgres:
    container_name: pendura_db
    image: postgres:8-alpine
    
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_HOST_PORT}:${DB_PORT}
    volumes:
      - api_db_data:/var/lib/postgresql/data
networks:
  backend:
volumes:
  api_db_data: